if(NOT DEFINED R2D_SOURCE_DIR)
    message(FATAL_ERROR "R2D_SOURCE_DIR is required")
endif()

if(NOT DEFINED R2D_BUILTIN_SHADER_OUTPUT)
    message(FATAL_ERROR "R2D_BUILTIN_SHADER_OUTPUT is required")
endif()

set(R2D_BUILTIN_SHADER_ENTRIES
    "CRT|crt|crt.fs"
    "RADIANCE_FLATLAND_CASCADE|radiance_flatland_cascade|radiance_flatland_cascade.fs"
    "RADIANCE_FLATLAND_RESOLVE|radiance_flatland_resolve|radiance_flatland_resolve.fs"
    "RADIANCE_BODY_GLOW|radiance_body_glow|radiance_body_glow.fs"
    "RADIANCE_FLATLAND_COMPOSE|radiance_flatland_compose|radiance_flatland_compose.fs"
)

file(WRITE "${R2D_BUILTIN_SHADER_OUTPUT}" "/* Generated by cmake/r2d_embed_shaders.cmake. Do not edit. */\n")
file(APPEND "${R2D_BUILTIN_SHADER_OUTPUT}" "#include \"r2d_builtin_shaders.h\"\n\n")

foreach(entry IN LISTS R2D_BUILTIN_SHADER_ENTRIES)
    string(REPLACE "|" ";" parts "${entry}")
    list(GET parts 0 enum_name)
    list(GET parts 2 file_name)

    set(shader_path "${R2D_SOURCE_DIR}/src/shaders/${file_name}")
    if(NOT EXISTS "${shader_path}")
        message(FATAL_ERROR "Missing built-in shader: ${shader_path}")
    endif()

    file(READ "${shader_path}" shader_hex HEX)
    string(LENGTH "${shader_hex}" shader_hex_length)

    file(APPEND "${R2D_BUILTIN_SHADER_OUTPUT}" "static const unsigned char R2D_SHADER_${enum_name}[] = {\n")
    set(column 0)

    if(shader_hex_length GREATER 0)
        math(EXPR byte_count "${shader_hex_length} / 2")
        math(EXPR last_index "${byte_count} - 1")

        foreach(index RANGE 0 ${last_index})
            math(EXPR pos "${index} * 2")
            string(SUBSTRING "${shader_hex}" ${pos} 2 byte)

            if(column EQUAL 0)
                file(APPEND "${R2D_BUILTIN_SHADER_OUTPUT}" "    ")
            endif()

            file(APPEND "${R2D_BUILTIN_SHADER_OUTPUT}" "0x${byte}, ")
            math(EXPR column "${column} + 1")

            if(column EQUAL 12)
                file(APPEND "${R2D_BUILTIN_SHADER_OUTPUT}" "\n")
                set(column 0)
            endif()
        endforeach()
    endif()

    if(NOT column EQUAL 0)
        file(APPEND "${R2D_BUILTIN_SHADER_OUTPUT}" "\n")
    endif()

    file(APPEND "${R2D_BUILTIN_SHADER_OUTPUT}" "    0x00\n};\n\n")
endforeach()

file(APPEND "${R2D_BUILTIN_SHADER_OUTPUT}" "const char *R2D_BuiltinShaderSource(R2D_BuiltinShader shader)\n{\n")
file(APPEND "${R2D_BUILTIN_SHADER_OUTPUT}" "    switch (shader) {\n")

foreach(entry IN LISTS R2D_BUILTIN_SHADER_ENTRIES)
    string(REPLACE "|" ";" parts "${entry}")
    list(GET parts 0 enum_name)
    file(APPEND "${R2D_BUILTIN_SHADER_OUTPUT}" "    case R2D_BUILTIN_SHADER_${enum_name}: return (const char *)R2D_SHADER_${enum_name};\n")
endforeach()

file(APPEND "${R2D_BUILTIN_SHADER_OUTPUT}" "    default: return \"\";\n")
file(APPEND "${R2D_BUILTIN_SHADER_OUTPUT}" "    }\n")
file(APPEND "${R2D_BUILTIN_SHADER_OUTPUT}" "}\n\n")

file(APPEND "${R2D_BUILTIN_SHADER_OUTPUT}" "const char *R2D_BuiltinShaderName(R2D_BuiltinShader shader)\n{\n")
file(APPEND "${R2D_BUILTIN_SHADER_OUTPUT}" "    switch (shader) {\n")

foreach(entry IN LISTS R2D_BUILTIN_SHADER_ENTRIES)
    string(REPLACE "|" ";" parts "${entry}")
    list(GET parts 0 enum_name)
    list(GET parts 1 label)
    file(APPEND "${R2D_BUILTIN_SHADER_OUTPUT}" "    case R2D_BUILTIN_SHADER_${enum_name}: return \"${label}\";\n")
endforeach()

file(APPEND "${R2D_BUILTIN_SHADER_OUTPUT}" "    default: return \"unknown\";\n")
file(APPEND "${R2D_BUILTIN_SHADER_OUTPUT}" "    }\n")
file(APPEND "${R2D_BUILTIN_SHADER_OUTPUT}" "}\n")
