if(NOT DEFINED R2D_DIST_TARGET)
    message(FATAL_ERROR "R2D_DIST_TARGET is required")
endif()

if(NOT DEFINED R2D_DIST_EXECUTABLE)
    message(FATAL_ERROR "R2D_DIST_EXECUTABLE is required")
endif()

if(NOT DEFINED R2D_DIST_SOURCE_DIR)
    message(FATAL_ERROR "R2D_DIST_SOURCE_DIR is required")
endif()

if(NOT DEFINED R2D_DIST_OUTPUT_DIR)
    message(FATAL_ERROR "R2D_DIST_OUTPUT_DIR is required")
endif()

if(NOT DEFINED R2D_DIST_CONFIG)
    set(R2D_DIST_CONFIG "Unknown")
endif()

set(R2D_DIST_TARGET_DIR "${R2D_DIST_OUTPUT_DIR}/${R2D_DIST_TARGET}")
set(R2D_DIST_SOURCE_BIN_DIR "")
get_filename_component(R2D_DIST_SOURCE_BIN_DIR "${R2D_DIST_EXECUTABLE}" DIRECTORY)

file(REMOVE_RECURSE "${R2D_DIST_TARGET_DIR}")
file(MAKE_DIRECTORY "${R2D_DIST_TARGET_DIR}")

file(COPY "${R2D_DIST_EXECUTABLE}" DESTINATION "${R2D_DIST_TARGET_DIR}")

set(R2D_DIST_PACK "${R2D_DIST_SOURCE_BIN_DIR}/${R2D_DIST_TARGET}.assets")
if(EXISTS "${R2D_DIST_PACK}")
    file(COPY "${R2D_DIST_PACK}" DESTINATION "${R2D_DIST_TARGET_DIR}")
elseif(EXISTS "${R2D_DIST_SOURCE_BIN_DIR}/assets")
    file(COPY "${R2D_DIST_SOURCE_BIN_DIR}/assets" DESTINATION "${R2D_DIST_TARGET_DIR}")
elseif(EXISTS "${R2D_DIST_SOURCE_DIR}/assets")
    file(COPY "${R2D_DIST_SOURCE_DIR}/assets" DESTINATION "${R2D_DIST_TARGET_DIR}")
endif()

if(EXISTS "${R2D_DIST_SOURCE_BIN_DIR}/r2d.ini")
    file(COPY "${R2D_DIST_SOURCE_BIN_DIR}/r2d.ini" DESTINATION "${R2D_DIST_TARGET_DIR}")
elseif(EXISTS "${R2D_DIST_SOURCE_DIR}/r2d.ini")
    file(COPY "${R2D_DIST_SOURCE_DIR}/r2d.ini" DESTINATION "${R2D_DIST_TARGET_DIR}")
endif()

if(EXISTS "${R2D_DIST_SOURCE_BIN_DIR}/locale")
    file(COPY "${R2D_DIST_SOURCE_BIN_DIR}/locale" DESTINATION "${R2D_DIST_TARGET_DIR}")
elseif(EXISTS "${R2D_DIST_SOURCE_DIR}/locale")
    file(COPY "${R2D_DIST_SOURCE_DIR}/locale" DESTINATION "${R2D_DIST_TARGET_DIR}")
endif()

if(EXISTS "${R2D_DIST_SOURCE_DIR}/assets/ATTRIBUTION.md")
    file(COPY "${R2D_DIST_SOURCE_DIR}/assets/ATTRIBUTION.md" DESTINATION "${R2D_DIST_TARGET_DIR}")
endif()

if(EXISTS "${R2D_DIST_SOURCE_DIR}/LICENSE")
    file(COPY "${R2D_DIST_SOURCE_DIR}/LICENSE" DESTINATION "${R2D_DIST_TARGET_DIR}")
elseif(EXISTS "${R2D_DIST_SOURCE_DIR}/LICENSE.md")
    file(COPY "${R2D_DIST_SOURCE_DIR}/LICENSE.md" DESTINATION "${R2D_DIST_TARGET_DIR}")
elseif(EXISTS "${R2D_DIST_SOURCE_DIR}/LICENSE.txt")
    file(COPY "${R2D_DIST_SOURCE_DIR}/LICENSE.txt" DESTINATION "${R2D_DIST_TARGET_DIR}")
endif()

if(EXISTS "${R2D_DIST_SOURCE_DIR}/assets/icon.ico")
    file(COPY "${R2D_DIST_SOURCE_DIR}/assets/icon.ico" DESTINATION "${R2D_DIST_TARGET_DIR}")
endif()

message(STATUS "R2D package ${R2D_DIST_TARGET} (${R2D_DIST_CONFIG}) -> ${R2D_DIST_TARGET_DIR}")
